
import type { PoolCosts } from "./types";

export const poolDigTypeMap: Record<string, string> = {
  "Bahamas 4": "Very Easy",
  "Bahamas 5": "Very Easy",
  "Bahamas 6": "Very Easy",
  "Bahamas 7": "Very Easy",
  "Bahamas 8": "Very Easy",
  "Santorini 7": "Very Easy",
  "Santorini 8": "Very Easy",
  "Santorini 9": "Very Easy",
  "Santorini 10": "Very Easy",
  "Santorini 11": "Very Easy",
  "Westminster 8": "Very Easy",
  "Westminster 9": "Very Easy",
  "Westminster 10": "Very Easy",
  "Westminster 11": "Very Easy",
  "Westminster 12": "Very Easy",
  "St Tropez 6": "Very Easy",
  "St Tropez 7": "Very Easy",
  "St Tropez 8": "Very Easy",
  "St Tropez 9": "Very Easy",
  "Amalfi 6": "Easy",
  "Amalfi 7": "Easy",
  "Amalfi 8": "Easy",
  "Amalfi 9": "Easy",
  "St Tropez 10": "Easy",
  "St Tropez 11": "Easy",
  "St Tropez 12": "Easy",
  "Capri 7": "Moderate",
  "Capri 8": "Moderate",
  "Capri 9": "Moderate",
  "Sicily 9": "Moderate",
  "Portofino 7": "Difficult",
  "Portofino 8": "Difficult",
  "Portofino 9": "Difficult",
  "Sicily 10": "Difficult",
  "Sicily 11": "Difficult",
  "Sicily 12": "Difficult",
  "Sorrento 7": "Difficult",
  "Sorrento 8": "Difficult",
  "Sorrento 9": "Difficult",
};

export const initialPoolCosts: Record<string, PoolCosts> = {
  "Westminster 8": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "Westminster 9": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "Westminster 10": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "Westminster 11": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "Westminster 12": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "Santorini 7": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "Santorini 8": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "Santorini 9": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "Santorini 10": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "Santorini 11": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },  
  "Bahamas 4": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "Bahamas 5": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "Bahamas 6": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "Bahamas 7": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "Bahamas 8": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "St Tropez 6": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "St Tropez 7": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "St Tropez 8": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "St Tropez 9": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "St Tropez 10": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "St Tropez 11": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "St Tropez 12": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "Amalfi 6": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "Amalfi 7": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "Amalfi 8": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "Amalfi 9": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "Capri 7": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "Capri 8": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "Capri 9": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "Sicily 9": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "Sicily 10": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "Sicily 11": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "Sicily 12": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "Portofino 7": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "Portofino 8": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "Portofino 9": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "Sorrento 7": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "Sorrento 8": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
  "Sorrento 9": { peaGravel: 0, installFee: 0, truckedWater: 0, saltBags: 0, misc: 2700, copingSupply: 0, beam: 0, copingLay: 0 },
};
