project_id = "mapshmozorhiewusdgor"
[functions.verify-cost-builder-password]
enabled = true
verify_jwt = true
import_map = "./functions/verify-cost-builder-password/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/verify-cost-builder-password/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/verify-cost-builder-password/*.html" ]
