// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mapshmozorhiewusdgor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hcHNobW96b3JoaWV3dXNkZ29yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3NTg5ODksImV4cCI6MjA1NTMzNDk4OX0.u6finPJTpAMxHYHEE3yVLqtlbuwIAIy4d94Wf_kx4wA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);