
import React, { useEffect, useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { FileText } from "lucide-react";

interface ProposalInfoSectionProps {
  owner1: string;
  owner2: string;
  proposalName: string;
  setProposalName: (value: string) => void;
  readonly?: boolean;
}

const ProposalInfoSection: React.FC<ProposalInfoSectionProps> = ({
  owner1,
  owner2,
  proposalName,
  setProposalName,
  readonly = false,
}) => {
  const [isAutoGenerated, setIsAutoGenerated] = useState(true);
  
  // Auto-generate proposal name when owner names change (if auto-generate is enabled)
  useEffect(() => {
    if (isAutoGenerated) {
      let generatedName = "";
      
      if (owner1 && owner2) {
        generatedName = `${owner1} & ${owner2} Pool Proposal`;
      } else if (owner1) {
        generatedName = `${owner1} Pool Proposal`;
      }
      
      setProposalName(generatedName);
    }
  }, [owner1, owner2, isAutoGenerated, setProposalName]);
  
  // When user manually edits, disable auto-generation
  const handleManualEdit = (e: React.ChangeEvent<HTMLInputElement>) => {
    setIsAutoGenerated(false);
    setProposalName(e.target.value);
  };
  
  return (
    <Card>
      <CardContent className="pt-6">
        <div className="flex items-center gap-2 mb-4">
          <FileText className="h-5 w-5 text-primary" />
          <h3 className="text-lg font-medium">Proposal Info</h3>
        </div>
        
        <div className="grid gap-2">
          <Label htmlFor="proposalName">Proposal Name</Label>
          <Input
            id="proposalName"
            value={proposalName}
            onChange={readonly ? undefined : handleManualEdit}
            placeholder="Proposal Name"
            readOnly={readonly}
            className={readonly ? "bg-gray-50 cursor-not-allowed" : ""}
          />
          <p className="text-sm text-muted-foreground">
            {isAutoGenerated 
              ? "Auto-generated from owner name(s). Edit to customize." 
              : "Manually edited."}
          </p>
        </div>
      </CardContent>
    </Card>
  );
};

export default ProposalInfoSection;
